name: Build and Release Executable

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --add-binary="C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\discord\bin\libopus-0.x64.dll;." src/main.py

      - name: Upload executable as release
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist/*.exe